server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fakhrichaerul/user-department-microservices-cloud-config
          clone-on-start: true
          searchPaths: '{application}'

      




